"""
Django settings for drankspel project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from drankspel.settings import *  # noqa

SECRET_KEY = "q^2soxp+5q=^lyxw$nyog+4x0lxfwmhf=_y$^4!$n(dlnvx&qa"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", "0.0.0.0"]

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080"
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"level": "INFO", "class": "logging.StreamHandler",},  # noqa
    },  # noqa
    "loggers": {
        "": {"handlers": ["console"], "level": "INFO", "propagate": True,},  # noqa
    },  # noqa
}

SPOTIFY_CACHE_PATH = os.path.join(BASE_DIR, "cache")  # noqa
