# Generated by Django 3.2.3 on 2021-05-27 19:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the item', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the drinking game.', max_length=1024)),
                ('description', tinymce.models.HTMLField(help_text='The description of how to play the drinking game.')),
                ('items', models.ManyToManyField(blank=True, help_text='The items needed to play this drinking game.', to='games.Item')),
            ],
        ),
    ]
